version: '3'
services:
  blockyworld-backend-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: blockyworld-backend-mongodb
    networks:
      - app-network

  blockyworld-backend-redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    container_name: blockyworld-backend-redis
    networks:
      - app-network

  blockyworld-backend-server:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - blockyworld-backend-mongodb
      - blockyworld-backend-redis
    container_name: blockyworld-backend-server
    volumes: 
      - .:/app
      - /app/node_modules
      - /etc/ssl/certs/localhost.pem:/etc/ssl/certs/localhost.pem:ro
      - /etc/ssl/private/localhost-key.pem:/etc/ssl/private/localhost-key.pem:ro
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge